### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by kame-0707** [kame-0707/graduation_bandmemo#28]
### 概要
卒業制作プロジェクト全体URL
https://github.com/users/kame-0707/projects/1/views/1

実装予定の機能と、必要なページを一覧でまとめました。
すでにチェックが入っている項目は、バトラン制作の際にすでに実装している機能です。
現時点での見積もり概算は下記のとおりです。

すでに実装した分の概算：60時間
6/26時点から本リリースまでの概算：102時間
6/26時点MVPまでの概算：40時間
※READMEの段階ではMVPまでの実装に「地図機能」「YouTubeの参考動画埋め込み機能」を入れておりましたが、本リリースに回す予定で概算を出しています。(メイン機能は決定事項メモ作成機能であるため)

ご確認のほど、よろしくお願いいたします。

### 実装予定の機能

【アプリケーションの雛形作成】
- [X] dockerを用いてrails new
- [X] render.comにデプロイ

【トップページの作成】
- [X] daisy UIのテーマカラーの選定
- [X] ヘッターの作成
- [X] フッターの作成
- [X] ロゴの作成
- [X] アプリの説明欄の作成

【会員登録】
- [X] sorceryのインストール
- [X] 新規登録画面のビューを作成

【ログイン機能_メールアドレス・パスワード認証】
- [X] ログイン用のビューページの作成

【ログイン機能_Google認証】
- [X] sorceryを用いてgoogle認証機能の実装
- [X] ログインページにgoogleログインボタンの設置

【音声メモ_投稿機能の実装】
- [X] voiceテーブルの作成
- [X] WebSpeech APIのドキュメント確認
- [X] ドキュメントのサンプルコードを元に、音声投稿機能の実装

【音声メモ_編集・削除機能】
- [X] 音声メモの編集機能の追加
- [X] 音声メモの削除機能の追加

【AI要約メモ_要約機能】
- [X] Open AI APIのAPIキー取得
- [X] summaryテーブルの作成
- [X] summaryコントローラーのcreateアクションに、ChatGPTの出力を受け取るコードを書く

【AI要約メモ_入力フォーム】
- [X] タイトルフォームの作成
- [X] 要約用メモフォームの作成
- [X] 「AIで要約」ボタンの設置
- [X] 「音声入力に戻る」のボタンの設置

【AI要約メモ_編集・削除機能】
- [X]  AI要約メモの編集機能の追加
- [X] AI要約メモの削除機能の追加

【AI要約メモ一覧】
- [X] AI要約メモ一覧のUIを整える
- [X]　「 原文はこちら」ボタンの設置
- [X] 「 原文はこちら」ボタンを押したときに遷移する、要約前の原文を確認できるページの設置

【ログイン機能_パスワードリセット機能】
- [ ] SorceryのReset passwordの機能を実装
- [ ] ApplicationMailerの設定
- [ ] LetterOpenerを用いた検証

【ログイン機能_ユーザー削除機能】
- [ ] ヘッダーのハンバーガーメニューに、ユーザー削除のリンクを設置

【プロフィール編集機能】
- [ ] プロフィール編集用のビュー画面の作成
- [ ] gem 'carrierwave'を導入して、プロフィール画像アップロード機能の作成
- [ ] Amazon S3の設定を行い、本番環境にプロフィール画像を設定できるようにする

【グループ作成・編集機能】
- [ ] groupテーブルの作成
- [ ] group_userテーブルの作成
- [ ] グループの作成機能の作成
- [ ] グループの一覧画面作成
- [ ] グループ編集機能(グループオーナーのみ編集可能)
- [ ] グループ詳細画面の作成

【グループ機能_参加・脱退・承認機能】
- [ ] 作成したグループに、メンバーが参加する機能
- [ ] 作成したグループから、メンバーが脱退する機能
- [ ] グループ参加の承認機能

【地図機能_一覧にスタジオを登録】
- [X] Google Maps APIのAPIキーを発行
- [X] Google Maps JavaScript APIを用いて、画面上に地図を表示
- [ ] 知名検索フォームと「検索する」ボタンの設置
- [ ] 場所一覧用のタイトル入力フォームの設置
- [ ] 「登録する」ボタンの設置
- [ ] 登録ボタンを押した後
  - [ ] Google Places APIを用いて、場所の詳細情報をdbに保存
  - [ ] 登録した場所にピンをたてる
  - [ ] ピンをクリックすると、吹き出しで場所名が表示される
  - [ ] 地図下部に、登録した場所を一覧で表示
 - [ ] 一覧の投稿をクリックすると、地図上に各投稿の場所が表示されるように設計
 
【地図機能_登録したスタジオの詳細画面の設計】
- [ ] スタジオ一覧の各投稿をクリックした際に遷移する、詳細ページの設計
  - [ ] 場所のタイトル_編集機能の設置
  - [ ] 場所に関する詳細メモフォーム・登録ボタンの設置
  - [ ] 場所に関する詳細メモ_編集機能の設置
  - [ ] 一覧に登録したスタジオ_削除機能の設置
  
【地図機能_現在地から目的のスタジオまでの道のり表示】
- [ ] 登録したピンをクリックした際に出るモーダルに、「googleマップで表示する」ボタンを追加する(→遷移先のgoogleマップアプリで同じ場所情報を表示し、必要に応じてユーザーに経路を検索してもらう)

【地図機能_近くにあるスタジオのレコメンド機能】
- [ ] Google Geolocation APIを用いて、現在地を取得
- [ ] 現在地周辺の音楽スタジオを、スライドできる形式で表示

【YouTube動画_投稿機能】
- [ ] videosテーブルの作成
- [ ] YouTubeのURL投稿用のフォーム作成
- [ ] 投稿タイトル用のフォーム作成
- [ ] 投稿ボタンの設置
- [ ] 各投稿に、各投稿者のプロフィール画像を設置

【YouTube動画_編集・削除機能】
- [ ] YouTube URL、投稿タイトルの編集機能の設置
- [ ] YouTube URL、投稿タイトルの削除機能の設置

【AI要約メモ_コメント機能(編集削除含む)】
 - [ ] 各投稿をクリックすると、詳細画面に遷移
   - [ ] 各投稿に対してコメントできる機能
   - [ ] 投稿されたコメントを編集できる機能
   - [ ] 投稿されたコメントを削除できる機能
   - [ ] コメント部分を、turbo_streamを用いて非同期処理できるように変更
 
【AI要約メモ_いいね機能】
- [ ] 各投稿に対して、ハートマークのいいねを押せる機能
- [ ] 各投稿に対して、ハートマークのいいねを削除できる機能
- [ ] いいねボタンの部分を、turbo_streamを用いて非同期処理できるように変更

【ログイン機能_LINE認証】
- [ ] sorceryを用いてLINE認証機能の実装
- [ ] ログインページにLINEログインボタンの設置

### 必要なページ

- [ ] トップページ
- [ ] ログイン画面
- [ ] 新規登録画面
- [ ] プロフィール表示画面(マイページ)
- [ ] プロフィール編集画面
- [ ] 地図機能_お気に入りスタジオ登録・一覧画面
- [ ] 地図機能_登録スタジオ編集・削除画面
- [ ] 音声メモ_一覧画面
- [ ] 音声メモ_編集・削除画面
- [ ] AI要約メモ_一覧画面
- [ ] AI要約メモ_編集画面
- [ ] AI要約メモ_原文表示画面
- [ ] AI要約メモ_詳細画面(コメント作成含む)
- [ ] AI要約メモ_コメント編集画面
- [ ] YouTube動画_一覧画面
- [ ] YouTube動画_編集画面

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
丁寧に作成できていていいと思います！
LGTMです！
