### ISSUE TITLE
MVPリリース_レビュー依頼

### ISSUE THREAD

**Issue by kame-0707** [kame-0707/graduation_bandmemo#32]
## 各種情報
サービス名：bandmemo
サービスURL：https://bandmemo-app.onrender.com/
GitHubリポジトリ：https://github.com/kame-0707/graduation_bandmemo

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] ログイン機能
- [X] メンバー招待機能
- [X] 決定事項メモ作成機能
  - [X] 音声による仮メモ作成機能
  - [X] フォーム入力機能
    - [X] Open AI APIによる要約アシスタント機能を導入
    - [X] 完成したメモを保存して投稿する機能
- [ ] 地図機能
  - [ ] 練習場所の情報を地図上から取得し、練習日時と共に登録して一覧表示する機能
  - [ ] 一覧の情報をLINEでシェアする機能
- [ ] YouTubeの参考動画埋め込み機能

## READMEレビュー時から変更した機能
■本リリースに回した機能
→コア機能はメンバー招待機能と決定事項メモ作成機能であるため、本リリースに回しました。
- [ ] 地図機能
  - [ ] 練習場所の情報を地図上から取得し、練習日時と共に登録して一覧表示する機能
  - [ ] 一覧の情報をLINEでシェアする機能
- [ ] YouTubeの参考動画埋め込み機能

■変更点
- ER図
  - groupsテーブルとvoicesテーブルに1対多のリレーションを追加
→グループ内でのページ遷移を円滑にするため
- READMEの詳細
  - 認証機能を、deviseからSorceryに変更
  →SNS認証のためにdeviseを使用予定であったが、Google認証とLINE認証のみであれば使用経験のあるSorceryでも実装可能と判断したため。
### バンドグループを作成・加入
- バンドグループを作成し、メンバー内だけで機能を利用できます。
- バンドごとや曲ごとに別のグループを作って練習メモの管理が可能。
- グループ詳細から加入申請を送り、オーナーに承認されれば既存のグループに加入することができます。
 [![Image from Gyazo](https://i.gyazo.com/d688b218a61924bc8c1bc7240f276c07.gif)](https://gyazo.com/d688b218a61924bc8c1bc7240f276c07)
### 音声文字起こしで仮メモ作成
- 練習中など、手入力が面倒な場面でも、音声文字起こし機能で仮メモの作成ができます。
- 作成されたテキストは編集可能です。
[![Image from Gyazo](https://i.gyazo.com/6a67dc88abf3ec5788d716a7c4c549cd.gif)](https://gyazo.com/6a67dc88abf3ec5788d716a7c4c549cd)
### メモを要約・保存
- 音声文字起こしで作成した仮メモをコピー&ペーストして、AIにまとめてもらいましょう。(入力例文でお試し要約も可能です。)
- 箇条書きで要点を押さえた書き方に変換。
- 原文テキストの確認、変換後テキストの編集が可能であるため、メモ内容を最終調整できます 。
### 練習メモ一覧
- 作成されたメモを一覧で確認。
- 分かりやすくまとめられたメモをグループ内で共有して、次回以降の練習に活かしましょう。
[![Image from Gyazo](https://i.gyazo.com/94cbe24fee138165d0eac4eb4bd40227.gif)](https://gyazo.com/94cbe24fee138165d0eac4eb4bd40227)

**Comment by kenchasonakai** [comment]
LGTMです！
